# permissions for end users to view azureidentityterminators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azureidentityterminator-viewer-role
rules:
- apiGroups:
  - aadpi-terminator.k8s.io
  resources:
  - azureidentityterminators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aadpi-terminator.k8s.io
  resources:
  - azureidentityterminators/status
  verbs:
  - get
