{{- if .Values.rbacRolesEnabled }}
# permissions for end users to edit azureidentityterminators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azureidentityterminator-editor-role
rules:
- apiGroups:
  - azidterminator.io
  resources:
  - azureidentityterminators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azidterminator.io
  resources:
  - azureidentityterminators/status
  verbs:
  - get
{{- end }}