# permissions for end users to edit azureidentityterminators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azid-terminator-editor-role
rules:
- apiGroups:
  - aadpi-terminator.k8s.io
  resources:
  - azureidentityterminators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aadpi-terminator.k8s.io
  resources:
  - azureidentityterminators/status
  verbs:
  - get
