
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azid-terminator-controller-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aadpodidentity.k8s.io
  resources:
  - azureidentities
  - azureidentitybindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azidterminator.io
  resources:
  - azureidentityterminators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azidterminator.io
  resources:
  - azureidentityterminators/finalizers
  verbs:
  - update
- apiGroups:
  - azidterminator.io
  resources:
  - azureidentityterminators/status
  verbs:
  - get
  - patch
  - update