# Default values for azure-identity-terminator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
namespace: azid-terminator-system
deployment: azid-terminator-controller

secrets:
  azureClientID:
  azureClientSecret:
  azureSubscriptionID:
  azureTenantID: